databases:
  - name: energiesdb
    plan: free
    databaseName: energies
    user: energies

services:
  - type: web
    plan: free
    name: energies
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn energies.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: energiesdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
